import { NextResponse } from "next/server";

export async function GET() {
  const movies = [
    { id: "1", image: "/images/movie-1.jpg", title: "The Shawshank Redemption", year: 1994, imdbScore: 0, baseScore: 0 },
    { id: "2", image: "/images/movie-2.jpg", title: "The Godfather", year: 1972, imdbScore: 0, baseScore: 0 },
    { id: "3", image: "/images/movie-3.jpg", title: "The Dark Knight", year: 2008, imdbScore: 0, baseScore: 0 },
    { id: "4", image: "/images/movie-4.jpg", title: "Schindler’s List", year: 1993, imdbScore: 0, baseScore: 0 },
    { id: "5", image: "/images/movie-5.jpg", title: "The Lord of the Rings: The Return of the King", year: 2003, imdbScore: 0, baseScore: 0 },
    { id: "6", image: "/images/movie-6.jpg", title: "12 Angry Men", year: 1957, imdbScore: 0, baseScore: 0 },
    { id: "7", image: "/images/movie-7.jpg", title: "The Godfather Part II", year: 1974, imdbScore: 0, baseScore: 0 },
    { id: "8", image: "/images/movie-8.jpg", title: "Pulp Fiction", year: 1994, imdbScore: 0, baseScore: 0 },
    { id: "9", image: "/images/movie-9.jpg", title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, imdbScore: 0, baseScore: 0 },
    { id: "10", image: "/images/movie-10.jpg", title: "12th Fail", year: 2023, imdbScore: 0, baseScore: 0 },
    { id: "11", image: "/images/movie-11.jpg", title: "Inception", year: 2010, imdbScore: 0, baseScore: 0 },
    { id: "12", image: "/images/movie-12.jpg", title: "Fight Club", year: 1999, imdbScore: 0, baseScore: 0 },
    { id: "13", image: "/images/movie-13.jpg", title: "Forrest Gump", year: 1994, imdbScore: 0, baseScore: 0 },
    { id: "14", image: "/images/movie-14.jpg", title: "The Good, the Bad and the Ugly", year: 1966, imdbScore: 0, baseScore: 0 },
    { id: "15", image: "/images/movie-15.jpg", title: "The Lord of the Rings: The Two Towers", year: 2002, imdbScore: 0, baseScore: 0 },
    { id: "16", image: "/images/movie-16.jpg", title: "Interstellar", year: 2014, imdbScore: 0, baseScore: 0 },
    { id: "17", image: "/images/movie-17.jpg", title: "Goodfellas", year: 1990, imdbScore: 0, baseScore: 0 },
    { id: "18", image: "/images/movie-18.jpg", title: "The Matrix", year: 1999, imdbScore: 0, baseScore: 0 },
    { id: "19", image: "/images/movie-19.jpg", title: "One Flew Over the Cuckoo’s Nest", year: 1975, imdbScore: 0, baseScore: 0 },
    { id: "20", image: "/images/movie-20.jpg", title: "Star Wars: Episode V - The Empire Strikes Back", year: 1980, imdbScore: 0, baseScore: 0 },
    { id: "21", image: "/images/movie-21.jpg", title: "Jai Bhim", year: 2021, imdbScore: 0, baseScore: 0 },
    { id: "22", image: "/images/movie-22.jpg", title: "Maharaja", year: 2024, imdbScore: 0, baseScore: 0 },
    { id: "23", image: "/images/movie-23.jpg", title: "The Silence of the Lambs", year: 1991, imdbScore: 0, baseScore: 0 },
    { id: "24", image: "/images/movie-24.jpg", title: "Se7en", year: 1995, imdbScore: 0, baseScore: 0 },
    { id: "25", image: "/images/movie-25.jpg", title: "Spider-Man: Across the Spider-Verse", year: 2023, imdbScore: 0, baseScore: 0 },
    { id: "26", image: "/images/movie-26.jpg", title: "Terminator 2: Judgment Day", year: 1991, imdbScore: 0, baseScore: 0 },
    { id: "27", image: "/images/movie-27.jpg", title: "City of God", year: 2002, imdbScore: 0, baseScore: 0 },
    { id: "28", image: "/images/movie-28.jpg", title: "The Green Mile", year: 1999, imdbScore: 0, baseScore: 0 },
    { id: "29", image: "/images/movie-29.jpg", title: "Star Wars: Episode IV - A New Hope", year: 1977, imdbScore: 0, baseScore: 0 },
    { id: "30", image: "/images/movie-30.jpg", title: "Spirited Away", year: 2001, imdbScore: 0, baseScore: 0 },
    { id: "31", image: "/images/movie-31.jpg", title: "Saving Private Ryan", year: 1998, imdbScore: 0, baseScore: 0 },
    { id: "32", image: "/images/movie-32.jpg", title: "Life Is Beautiful", year: 1997, imdbScore: 0, baseScore: 0 },
    { id: "33", image: "/images/movie-33.jpg", title: "Harakiri", year: 1962, imdbScore: 0, baseScore: 0 },
    { id: "34", image: "/images/movie-34.jpg", title: "The Pianist", year: 2002, imdbScore: 0, baseScore: 0 },
    { id: "35", image: "/images/movie-35.jpg", title: "Back to the Future", year: 1985, imdbScore: 0, baseScore: 0 },
    { id: "36", image: "/images/movie-36.jpg", title: "The Usual Suspects", year: 1995, imdbScore: 0, baseScore: 0 },
    { id: "37", image: "/images/movie-37.jpg", title: "Psycho", year: 1960, imdbScore: 0, baseScore: 0 },
    { id: "38", image: "/images/movie-38.jpg", title: "The Lion King", year: 1994, imdbScore: 0, baseScore: 0 },
    { id: "39", image: "/images/movie-39.jpg", title: "Modern Times", year: 1936, imdbScore: 0, baseScore: 0 },
    { id: "40", image: "/images/movie-40.jpg", title: "Grave of the Fireflies", year: 1988, imdbScore: 0, baseScore: 0 },
    { id: "41", image: "/images/movie-41.jpg", title: "American History X", year: 1998, imdbScore: 0, baseScore: 0 },
    { id: "42", image: "/images/movie-42.jpg", title: "Whiplash", year: 2014, imdbScore: 0, baseScore: 0 },
    { id: "43", image: "/images/movie-43.jpg", title: "Gladiator", year: 2000, imdbScore: 0, baseScore: 0 },
    { id: "44", image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/City_Lights_(1931_theatrical_poster).jpg", title: "City Lights", year: 1931, imdbScore: 0, baseScore: 0 },
    { id: "45", image: "/images/movie-45.jpg", title: "The Departed", year: 2006, imdbScore: 0, baseScore: 0 },
    { id: "46", image: "/images/movie-46.jpg", title: "The Intouchables", year: 2011, imdbScore: 0, baseScore: 0 },
    { id: "47", image: "/images/movie-47.jpg", title: "The Prestige", year: 2006, imdbScore: 0, baseScore: 0 },
    { id: "48", image: "/images/movie-48.jpg", title: "Casablanca", year: 1942, imdbScore: 0, baseScore: 0 },
    { id: "49", image: "/images/movie-49.jpg", title: "Once Upon a Time in the West", year: 1968, imdbScore: 0, baseScore: 0 },
    { id: "50", image: "/images/movie-50.jpg", title: "Rear Window", year: 1954, imdbScore: 0, baseScore: 0 },
    { id: "51", image: "/images/movie-51.jpg", title: "Cinema Paradiso", year: 1988, imdbScore: 0, baseScore: 0 },
    { id: "52", image: "/images/movie-52.jpg", title: "Alien", year: 1979, imdbScore: 0, baseScore: 0 },
    { id: "53", image: "/images/movie-53.jpg", title: "Apocalypse Now", year: 1979, imdbScore: 0, baseScore: 0 },
    { id: "54", image: "/images/movie-54.jpg", title: "Memento", year: 2000, imdbScore: 0, baseScore: 0 },
    { id: "55", image: "/images/movie-55.jpg", title: "Raiders of the Lost Ark", year: 1981, imdbScore: 0, baseScore: 0 },
    { id: "56", image: "/images/movie-56.jpg", title: "The Great Dictator", year: 1940, imdbScore: 0, baseScore: 0 },
    { id: "57", image: "/images/movie-57.jpg", title: "Django Unchained", year: 2012, imdbScore: 0, baseScore: 0 },
    { id: "58", image: "/images/movie-58.jpg", title: "Paths of Glory", year: 1957, imdbScore: 0, baseScore: 0 },
    { id: "59", image: "/images/movie-59.jpg", title: "WALL·E", year: 2008, imdbScore: 0, baseScore: 0 },
    { id: "60", image: "/images/movie-60.jpg", title: "Witness for the Prosecution", year: 1957, imdbScore: 0, baseScore: 0 },
    { id: "61", image: "/images/movie-61.jpg", title: "The Shining", year: 1980, imdbScore: 0, baseScore: 0 },
    { id: "62", image: "/images/movie-62.jpg", title: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", year: 1964, imdbScore: 0, baseScore: 0 },
    { id: "63", image: "/images/movie-63.jpg", title: "Sunset Boulevard", year: 1950, imdbScore: 0, baseScore: 0 },
    { id: "64", image: "/images/movie-64.jpg", title: "V for Vendetta", year: 2005, imdbScore: 0, baseScore: 0 },
    { id: "65", image: "/images/movie-65.jpg", title: "Oldboy", year: 2003, imdbScore: 0, baseScore: 0 },
    { id: "66", image: "/images/movie-66.jpg", title: "Princess Mononoke", year: 1997, imdbScore: 0, baseScore: 0 },
    { id: "67", image: "/images/movie-67.jpg", title: "Amélie", year: 2001, imdbScore: 0, baseScore: 0 },
    { id: "68", image: "/images/movie-68.jpg", title: "Toy Story", year: 1995, imdbScore: 0, baseScore: 0 },
    { id: "69", image: "/images/movie-69.jpg", title: "Das Boot", year: 1981, imdbScore: 0, baseScore: 0 },
    { id: "70", image: "/images/movie-70.jpg", title: "North by Northwest", year: 1959, imdbScore: 0, baseScore: 0 },
    { id: "71", image: "/images/movie-71.jpg", title: "Inglourious Basterds", year: 2009, imdbScore: 0, baseScore: 0 },
    { id: "72", image: "/images/movie-72.jpg", title: "The Apartment", year: 1960, imdbScore: 0, baseScore: 0 },
    { id: "73", image: "/images/movie-73.jpg", title: "Timbuktu", year: 2014, imdbScore: 0, baseScore: 0 },
    { id: "74", image: "/images/movie-74.jpg", title: "Requiem for a Dream", year: 2000, imdbScore: 0, baseScore: 0 },
    { id: "75", image: "/images/movie-75.jpg", title: "Braveheart", year: 1995, imdbScore: 0, baseScore: 0 },
    { id: "76", image: "/images/movie-76.jpg", title: "Snatch", year: 2000, imdbScore: 0, baseScore: 0 },
    { id: "77", image: "/images/movie-77.jpg", title: "Full Metal Jacket", year: 1987, imdbScore: 0, baseScore: 0 },
    { id: "78", image: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Metropolis_(1927_film_poster).jpg", title: "Metropolis", year: 1927, imdbScore: 0, baseScore: 0 },
    { id: "79", image: "/images/movie-79.jpg", title: "3 Idiots", year: 2009, imdbScore: 0, baseScore: 0 },
    { id: "80", image: "/images/movie-80.jpg", title: "Monty Python and the Holy Grail", year: 1975, imdbScore: 0, baseScore: 0 },
    { id: "81", image: "/images/movie-81.jpg", title: "Double Indemnity", year: 1944, imdbScore: 0, baseScore: 0 },
    { id: "82", image: "/images/movie-82.jpg", title: "Eternal Sunshine of the Spotless Mind", year: 2004, imdbScore: 0, baseScore: 0 },
    { id: "83", image: "/images/movie-83.jpg", title: "Up", year: 2009, imdbScore: 0, baseScore: 0 },
    { id: "84", image: "/images/movie-84.jpg", title: "Rashomon", year: 1950, imdbScore: 0, baseScore: 0 },
    { id: "85", image: "/images/movie-85.jpg", title: "The Sting", year: 1973, imdbScore: 0, baseScore: 0 },
    { id: "86", image: "/images/movie-86.jpg", title: "To Kill a Mockingbird", year: 1962, imdbScore: 0, baseScore: 0 },
    { id: "87", image: "/images/movie-87.jpg", title: "Downfall", year: 2004, imdbScore: 0, baseScore: 0 },
    { id: "88", image: "/images/movie-88.jpg", title: "Amadeus", year: 1984, imdbScore: 0, baseScore: 0 },
    { id: "89", image: "/images/movie-89.jpg", title: "The Bicycle Thieves", year: 1948, imdbScore: 0, baseScore: 0 },
    { id: "90", image: "/images/movie-90.jpg", title: "Heat", year: 1995, imdbScore: 0, baseScore: 0 },
    { id: "91", image: "/images/movie-91.jpg", title: "Fargo", year: 1996, imdbScore: 0, baseScore: 0 },
    { id: "92", image: "/images/movie-92.jpg", title: "The Wolf of Wall Street", year: 2013, imdbScore: 0, baseScore: 0 },
    { id: "93", image: "/images/movie-93.jpg", title: "Inside Out", year: 2015, imdbScore: 0, baseScore: 0 },
    { id: "94", image: "/images/movie-94.jpg", title: "No Country for Old Men", year: 2007, imdbScore: 0, baseScore: 0 },
    { id: "95", image: "/images/movie-95.jpg", title: "Incendies", year: 2010, imdbScore: 0, baseScore: 0 },
    { id: "96", image: "/images/movie-96.jpg", title: "Pather Panchali", year: 1955, imdbScore: 0, baseScore: 0 },
    { id: "97", image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/The_Kid_(1921_poster).jpg", title: "The Kid", year: 1921, imdbScore: 0, baseScore: 0 },
    { id: "98", image: "/images/movie-98.jpg", title: "Taxi Driver", year: 1976, imdbScore: 0, baseScore: 0 },
    { id: "99", image: "/images/movie-99.jpg", title: "Gran Torino", year: 2008, imdbScore: 0, baseScore: 0 },
    { id: "100", image: "/images/movie-100.jpg", title: "Mad Max: Fury Road", year: 2015, imdbScore: 0, baseScore: 0 }
  ];
  return NextResponse.json(
    movies.map((movie) => ({
      ...movie,
      imdbUrl: `https://www.imdb.com/title/${movie.id}`
    }))
  );
}
